---
title: Free Nonprofit Starter Website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
org_name: Project Example
org_summary: 'A mobile-friendly Github Pages template designed to help grassroots
  nonprofits get a website online quickly

'
org_full_description: 'Ipsum dolor sit amet, consectetur adipisicing elit, sed do
  eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  Duis aute irure dolor in reprehenderit in voluptate.

'
org_general_email_inbox: your-email@somedomain.com
org_street_address: 1355 Market Street
org_address_suite: Suite 900
org_city: San Francisco
org_state: CA
org_zip: '94103

'
org_phone: "(123) 456-7890\n"
org_twitter_username: smartergiving
org_facebook_username: smartergiving
org_instagram_username: 
fiscal_sponsor: false
fiscal_sponsor_name: 
is_501c3: true
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits
publish: false
color_scheme: default
baseurl: ''
markdown: kramdown
kramdown:
  input: GFM
sass:
  sass_dir: assets/_sass
  style: compressed
paypal_button_id: 
smartergiving_id: 
